# This is a config for E2B sandbox template.
# You can use template ID (wxe2y93k4kafhbwqg2br) or template name (expo-testing) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("expo-testing") # Sync sandbox
# sandbox = await AsyncSandbox.create("expo-testing") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('expo-testing')

team_id = "ca97f034-46fd-4f61-96f8-a31147b4e6eb"
memory_mb = 4_096
cpu_count = 4
dockerfile = "templates/expo-template/e2b.Dockerfile"
template_name = "expo-testing"
template_id = "wxe2y93k4kafhbwqg2br"
